name: Tests unitaire 

on: push 

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - run: python my_script.py
    - name: Installation des dépendances
      run: npm install
    - name: Execution des tests unitaire 
      run: npm test
    - name: Execution du code coverage
      run: pytest
    - name: Récupération du rapport
      uses: actions/upload-artifact@v3
      with:
        name: reports 
        path: ./reports/**