name: Tests unitaire 

on: push 

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récuperation du repository
        uses: actions/checkout@v1
      - name: Installation de python
        uses: actions/setup-python
        with:
          python-version: '3.x' 
      - run: python my_script.py
      
      - name: Récupération du rapport
        uses: actions/upload-artifact@v3
        with:
          name: reports 
          path: ./reports/**