name: test automatique 
on:
  push:
jobs:
  tests-app:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: ['2.7', '3.7', '3.9']
    steps: 
      - name: Récupération du répository 
        uses: actions/checkout@v3
      - name: installation de python 
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Info sur la version testé 
        run: echo ${{ matrix.python-version }}
      - name: Install des dépendances 
        run: pip install -r requirements.txt
      - name: Execution du code coverage
        run: pytest
      - name: Récupération du rapport 
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./reports/**
  build-app:
    needs: Tests-app
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v3
      - name: Installation de QEMU
        uses: docker/sutup-qemu-action@v1
      - name: Installation de docker BuildX
        uses: docker/sutup-buildx-action@
      - name: Login au docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Build & push docker
        uses: docker/build-puch-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/weather:${{ env.APP_VERSION }}